run:
  skip-dirs-use-default: true
  timeout: 1m

service:
  golangci-lint-version: 1.42.x

linters:
  enable:
    - gofmt
    - gosec
    - misspell
    - goconst
    - dogsled
    - bodyclose
    - unconvert
    - predeclared
    - revive
